using System.Text;
using System.Text.RegularExpressions;
using Transpiler.Core;
using Transpiler.Core.Model;

namespace Transpiler.CodeGen.CSharp.ProjectShapes;

internal static partial class ProjectShapeHelpers
{
    [GeneratedRegex("[^a-zA-Z0-9]+")]
    private static partial Regex NonAlphaNumeric();

    public static string ProjectName(WorkflowGraph graph)
    {
        var cleaned = NonAlphaNumeric().Replace(graph.Name.Trim(), "");
        return string.IsNullOrEmpty(cleaned) ? "GeneratedWorkflow" : cleaned;
    }

    public static string UsingsBlock(CodeGenContext ctx)
    {
        var sb = new StringBuilder();
        foreach (var ns in ctx.UsingDirectives.OrderBy(n => n, StringComparer.Ordinal))
        {
            sb.AppendLine($"using {ns};");
        }

        return sb.ToString();
    }

    public static string Readme(WorkflowGraph graph, CodeGenContext ctx, string shapeDescription)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {graph.Name}");
        sb.AppendLine();
        sb.AppendLine($"Generated by WorkflowForge from an n8n workflow export. {shapeDescription}");
        sb.AppendLine();
        sb.AppendLine("No n8n runtime dependency is required to run this project — `dotnet run` after `dotnet restore`.");
        sb.AppendLine();

        sb.AppendLine("## Follow-up needed");
        sb.AppendLine();
        if (ctx.Warnings.Count == 0)
        {
            sb.AppendLine("- None — every node in this workflow was fully translated.");
        }
        else
        {
            foreach (var warning in ctx.Warnings)
            {
                sb.AppendLine($"- {warning}");
            }
        }

        sb.AppendLine();
        sb.AppendLine("Credentials referenced by the original workflow (if any) are read from configuration "
                       + "(environment variables / `appsettings.json` / user-secrets) by a placeholder name — "
                       + "never inlined. Check `Program.cs` for the exact names expected.");

        return sb.ToString();
    }
}
