using Transpiler.Core;
using Transpiler.Core.Model;
using Transpiler.CodeGen.CSharp.Emission;

namespace Transpiler.CodeGen.CSharp.NodeEmitters;

/// <summary>The actual timer loop is generated by <c>WorkerProjectShape</c>; this only seeds the first item per tick.</summary>
public sealed class ScheduleTriggerEmitter : INodeEmitter
{
    public IReadOnlyList<string> SupportedSourceTypes { get; } = ["n8n-nodes-base.scheduletrigger"];

    public EmittedNode Emit(WorkflowNode node, WorkflowGraph graph, CodeGenContext ctx)
    {
        var varName = ctx.Names.Register(node.Id, node.Name);
        ctx.Names.AdvanceCurrent(varName);

        return new EmittedNode
        {
            NodeId = node.Id,
            Kind = EmittedNodeKind.Statement,
            Comment = $"Schedule trigger: {node.Name}",
            Lines = [$"var {varName} = new JsonObject();"],
        };
    }
}
