using Transpiler.Core;
using Transpiler.Core.Model;
using Transpiler.CodeGen.CSharp.Emission;

namespace Transpiler.CodeGen.CSharp.NodeEmitters;

/// <summary>
/// The route registration itself (<c>app.MapPost(...)</c>) is generated by
/// <c>MinimalApiProjectShape</c> from this node's parameters — this emitter only produces the
/// statement that turns the incoming request into the pipeline's first item, assuming an
/// <c>HttpRequest request</c> is in scope (true inside the route handler the project shape builds).
/// </summary>
public sealed class WebhookTriggerEmitter : INodeEmitter
{
    public IReadOnlyList<string> SupportedSourceTypes { get; } = ["n8n-nodes-base.webhook"];

    public EmittedNode Emit(WorkflowNode node, WorkflowGraph graph, CodeGenContext ctx)
    {
        var varName = ctx.Names.Register(node.Id, node.Name);
        ctx.Names.AdvanceCurrent(varName);
        ctx.UsingDirectives.Add("System.Text.Json.Nodes");

        return new EmittedNode
        {
            NodeId = node.Id,
            Kind = EmittedNodeKind.Statement,
            Comment = $"Webhook trigger: {node.Name}",
            Lines =
            [
                $"var {varName} = new JsonObject();",
                $"{varName}[\"body\"] = await JsonNode.ParseAsync(request.Body) ?? new JsonObject();",
                $"{varName}[\"query\"] = new JsonObject(request.Query.Select(q => KeyValuePair.Create<string, JsonNode?>(q.Key, q.Value.ToString())));",
            ],
        };
    }
}
